import { useState } from "react";
import { Icon } from "../App";
import type { SearchMatch, TreeEntry } from "../ide";
import type { GitSummary } from "../system";
import { describeTool, type AgentSession, type CodeIndex } from "../intelligence";
import { projectName } from "../settings";
import type { ActivityView } from "./ActivityBar";

interface Props { view: ActivityView; width: number; tree: TreeEntry[]; recentProjects: string[]; currentProject?: string; searchResults: SearchMatch[]; git?: GitSummary; index?: CodeIndex; agents: AgentSession[]; onSearch: (query: string) => void; onReplace: (query: string, replacement: string) => void; onRefreshGit: () => void; onStageAll: () => void; onCommit: () => void; onApplyPatch: (patch: string, reverse: boolean) => void; onRollback: () => void; onBuildIndex: () => void; onStartAgent: (objective: string) => void; onAdvanceAgent: (session: AgentSession) => void; onPauseAgent: (session: AgentSession) => void; onCancelAgent: (id: number) => void; onRetryAgent: (id: number) => void; onExportAudit: () => void; onOpenProject: () => void; onSelectProject: (path: string) => void; onOpenFile: (path: string, line?: number) => void; onMutate: (kind: "file" | "folder" | "rename" | "delete", selected?: string) => void; }

export function SidePanel(props: Props) {
  const [selected, setSelected] = useState<string>();
  const [query, setQuery] = useState("");
  const [replacement, setReplacement] = useState("");
  const [patch, setPatch] = useState("");
  const [objective, setObjective] = useState("");
  const title = { explorer: "Explorer", search: "Search", source: "Source control", agent: "Agent history" }[props.view];
  return <aside className="side-panel" aria-label={title} style={{ width: props.width }}><p className="panel-title">{title}</p>
    {props.view === "explorer" && <>{props.currentProject ? <><div className="explorer-toolbar"><strong title={props.currentProject}>{projectName(props.currentProject)}</strong><span><button title="New file" onClick={() => props.onMutate("file")}>＋F</button><button title="New folder" onClick={() => props.onMutate("folder")}>＋D</button><button title="Rename selected" disabled={!selected} onClick={() => props.onMutate("rename", selected)}>✎</button><button title="Delete selected" disabled={!selected} onClick={() => props.onMutate("delete", selected)}>⌫</button></span></div><div className="file-tree" role="tree"><Tree entries={props.tree} selected={selected} onSelect={setSelected} onOpen={props.onOpenFile} /></div></> : <><button className="open-button" onClick={props.onOpenProject}><Icon name="folder" /> Open project</button><div className="section-label">Recent</div>{props.recentProjects.length === 0 ? <p className="empty-copy">Your recent projects will appear here.</p> : <ul className="recent-list">{props.recentProjects.map((path) => <li key={path}><button title={path} onClick={() => props.onSelectProject(path)}><Icon name="folder" /><span><strong>{projectName(path)}</strong><small>{path}</small></span></button></li>)}</ul>}</>}</>}
    {props.view === "search" && <div className="search-panel"><form onSubmit={(event) => { event.preventDefault(); void props.onSearch(query); }}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search files" aria-label="Search files" /><button aria-label="Run search"><Icon name="search" /></button></form><div className="replace-row"><input value={replacement} onChange={(event) => setReplacement(event.target.value)} placeholder="Replace with" aria-label="Replace with" /><button disabled={!query} onClick={() => props.onReplace(query, replacement)}>Replace all</button></div><p className="result-count">{props.searchResults.length} results</p><ul>{props.searchResults.map((match) => <li key={`${match.path}:${match.line}`}><button onClick={() => props.onOpenFile(match.path, match.line)}><strong>{match.path}:{match.line}</strong><span>{match.preview}</span></button></li>)}</ul></div>}
    {props.view === "source" && <div className="git-panel"><div className="patch-actions"><button className="git-refresh" onClick={props.onRefreshGit}>Refresh</button><button onClick={props.onStageAll}>Stage all</button><button onClick={props.onCommit}>Commit</button></div>{props.git ? <><p className="git-branch"><Icon name="branch" /> {props.git.branch}</p><div className="section-label">Changes · {props.git.changes.length}</div><ul>{props.git.changes.length ? props.git.changes.map((change) => <li key={change}>{change}</li>) : <li className="clean">Working tree clean</li>}</ul><div className="section-label">Unstaged diff</div><pre>{props.git.diff || "No unstaged changes"}</pre><div className="section-label">Structured patch</div><textarea value={patch} onChange={(event) => setPatch(event.target.value)} placeholder="Paste a unified Git patch to validate…" aria-label="Unified patch"/><div className="patch-actions"><button onClick={() => props.onApplyPatch(patch, false)}>Check & apply</button><button onClick={() => props.onApplyPatch(patch, true)}>Reverse</button><button onClick={props.onRollback}>Rollback last task</button></div></> : <p className="empty-copy">Open a Git repository to inspect source control.</p>}</div>}
    {props.view === "agent" && <div className="agent-sessions"><div className="index-summary"><strong>Local index</strong>{props.index ? <><span>{props.index.files.length} files · {props.index.symbols.length} symbols</span><small>{[...props.index.profile.languages, ...props.index.profile.frameworks].join(" · ") || "Text project"}</small><div className="index-symbols">{props.index.symbols.slice(0, 20).map((symbol) => <button key={`${symbol.path}:${symbol.line}:${symbol.name}`} title={symbol.signature} onClick={() => props.onOpenFile(symbol.path, symbol.line)}><b>{symbol.name}</b><span>{symbol.kind} · {symbol.path}:{symbol.line}</span></button>)}</div></> : <span>Not built</span>}<button onClick={props.onBuildIndex}>Rebuild index</button></div><form onSubmit={(event) => { event.preventDefault(); if (objective.trim()) { props.onStartAgent(objective); setObjective(""); } }}><textarea value={objective} onChange={(event) => setObjective(event.target.value)} placeholder="Describe a repository task…" aria-label="Agent objective"/><button disabled={!objective.trim()}>Start local agent</button></form><div className="section-label">Sessions</div><button onClick={props.onExportAudit}>Export audit log</button>{props.agents.length === 0 ? <p className="empty-copy">No agent sessions yet.</p> : props.agents.map((session) => <article className="agent-session" key={session.id}><header><strong>#{session.id} · {session.phase}</strong><span>step {session.step}</span></header><p>{session.objective}</p>{session.pendingTool && <pre aria-label="Pending agent action">{describeTool(session.pendingTool)}</pre>}<ul>{session.observations.map((item) => <li key={item.step}>{item.summary}</li>)}</ul><div>{!["completed", "failed", "cancelled"].includes(session.phase) && <><button onClick={() => props.onAdvanceAgent(session)}>{session.phase === "awaitingApproval" ? "Review & approve" : "Continue"}</button><button onClick={() => props.onPauseAgent(session)}>{session.phase === "paused" ? "Resume" : "Pause"}</button><button onClick={() => props.onCancelAgent(session.id)}>Cancel</button></>}{session.phase === "failed" && <button onClick={() => props.onRetryAgent(session.id)}>Retry</button>}</div></article>)}</div>}
  </aside>;
}

function Tree({ entries, selected, onSelect, onOpen }: { entries: TreeEntry[]; selected?: string; onSelect: (path: string) => void; onOpen: (path: string) => void }) {
  return <ul>{entries.map((entry) => <li key={entry.path}>{entry.isDirectory ? <details open><summary className={selected === entry.path ? "selected" : ""} onClick={() => onSelect(entry.path)}><span>⌄</span> 📁 {entry.name}</summary><Tree entries={entry.children} selected={selected} onSelect={onSelect} onOpen={onOpen} /></details> : <button className={selected === entry.path ? "selected" : ""} onClick={() => { onSelect(entry.path); onOpen(entry.path); }} title={entry.path}><span className="file-glyph">{fileGlyph(entry.name)}</span>{entry.name}</button>}</li>)}</ul>;
}

const fileGlyph = (name: string) => ({ ts: "TS", tsx: "TS", js: "JS", jsx: "JS", rs: "RS", py: "PY", java: "JV", json: "{}", md: "MD", css: "#" } as Record<string, string>)[name.split(".").at(-1)?.toLowerCase() ?? ""] ?? "·";
