import { useRef } from "react";
import type { CSSProperties, PointerEvent as ReactPointerEvent } from "react";
import { Icon } from "../App";
import { projectName, type Settings } from "../settings";
interface Props { project?: string; sidebarWidth: number; agentWidth: number; bottomHeight: number; onResize: (settings: Partial<Settings>) => void; onOpenProject: () => void; }
export function Workbench({ project, sidebarWidth, agentWidth, bottomHeight, onResize, onOpenProject }: Props) {
  const ref = useRef<HTMLDivElement>(null);
  const startDrag = (kind: "sidebar" | "agent" | "bottom", event: ReactPointerEvent) => { event.currentTarget.setPointerCapture(event.pointerId); const bounds = ref.current?.getBoundingClientRect(); const move = (moveEvent: PointerEvent) => { if (!bounds) return; if (kind === "sidebar") onResize({ sidebarWidth: clamp(moveEvent.clientX - 50, 200, 420) }); if (kind === "agent") onResize({ agentWidth: clamp(bounds.right - moveEvent.clientX, 260, 520) }); if (kind === "bottom") onResize({ bottomPanelHeight: clamp(bounds.bottom - moveEvent.clientY, 120, 420) }); }; const stop = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", stop); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", stop); };
  return <div className="workbench" ref={ref} style={{ "--agent-width": `${agentWidth}px`, "--bottom-height": `${bottomHeight}px` } as CSSProperties}><div className="resize-handle sidebar-resize" role="separator" aria-label="Resize sidebar" aria-orientation="vertical" aria-valuenow={sidebarWidth} tabIndex={0} onPointerDown={(event) => startDrag("sidebar", event)} /><section className="editor-area" aria-label="Editor"><div className="tab-strip"><span className="welcome-tab">Welcome <span>×</span></span></div><div className="welcome-view"><div className="welcome-content"><span className="welcome-mark">H</span><p className="overline">Local coding intelligence</p><h1>{project ? projectName(project) : "Welcome to Helel"}</h1><p>{project ? "The workspace shell is ready. File exploration and editing arrive in Phase 2." : "Open a local project to begin. Helel keeps project history and preferences on this device."}</p>{!project && <button className="primary-button" onClick={onOpenProject}><Icon name="folder" /> Open project</button>}<div className="privacy-note"><span className="privacy-dot" /> Offline by default · no telemetry</div></div></div></section><div className="resize-handle agent-resize" role="separator" aria-label="Resize agent panel" aria-orientation="vertical" aria-valuenow={agentWidth} tabIndex={0} onPointerDown={(event) => startDrag("agent", event)} /><aside className="agent-panel" aria-label="Helel agent" style={{ width: agentWidth }}><div className="agent-heading"><span><Icon name="agent" /> Helel</span><span className="phase-badge">Shell</span></div><div className="agent-empty"><div className="agent-orb"><Icon name="agent" /></div><h2>Agent workspace</h2><p>Planning, tools, and model integration arrive in later phases.</p></div><div className="prompt-placeholder" aria-disabled="true"><span>Describe a coding task…</span><kbd>⌘ ↵</kbd></div></aside><div className="resize-handle bottom-resize" role="separator" aria-label="Resize bottom panel" aria-orientation="horizontal" aria-valuenow={bottomHeight} tabIndex={0} onPointerDown={(event) => startDrag("bottom", event)} /><section className="bottom-panel" aria-label="Terminal and problems" style={{ height: bottomHeight }}><div className="bottom-tabs"><button className="active"><Icon name="terminal" /> Terminal</button><button>Problems <span className="count">0</span></button><button>Output</button></div><div className="terminal-empty"><span className="prompt">›</span><span>Terminal execution arrives in Phase 3.</span></div></section></div>;
}
const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));
